Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -9,7 +9,30 @@ jobs:
       uses: actions/setup-ruby@v1
       with:
         ruby-version: 3.0
-    - run: |
+    - name: Install dependencies
+      run: |
+        rvm gemset create puppet-check
         gem install bundle
+    - name: validation
+      run: |
         bundle
         bundle exec rake validate
+        if [ $? -eq 0 ]; then
+            echo "Validate checks passed!"
+          else
+            echo "Validate checks failed!"
+            rvm gemset delete puppet-check --force
+            exit 1
+        fi
+		    bundle exec rake strings:generate
+        bundle exec rake lint
+        if [ $? -eq 0 ]; then
+          echo "Lint checks passed!"
+        else
+          echo "Lint checks failed"
+          rvm gemset delete puppet-check --force
+          exit 1
+        fi
+        rvm gemset delete puppet-check --force
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
